<?xml version="1.0" encoding="utf-8"?><Database Name="extrados" Class="dbExtradosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NOTEBENJA;Initial Catalog=extrados;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="extradosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RazonSocial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Cliente_Pedido" Member="Pedidos" ThisKey="Codigo" OtherKey="CodigoCliente" Type="Pedido" />
      <Association Name="Usuario_Cliente" Member="Usuario" ThisKey="IdUsuario" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdRol" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Member="Usuario1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Cliente" Member="Clientes" ThisKey="Id" OtherKey="IdUsuario" Type="Cliente" />
      <Association Name="Role_Usuario" Member="Role" ThisKey="IdRol" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetallesPedidos" Member="DetallesPedidos">
    <Type Name="DetallesPedido">
      <Column Name="NumeroPedido" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroItem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodigoProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_DetallesPedido" Member="Pedido" ThisKey="NumeroPedido" OtherKey="NumeroPedido" Type="Pedido" IsForeignKey="true" />
      <Association Name="Producto_DetallesPedido" Member="Producto" ThisKey="CodigoProducto" OtherKey="Codigo" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Marcas" Member="Marcas">
    <Type Name="Marca">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Marca_Producto" Member="Productos" ThisKey="Id" OtherKey="IdMarca" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Pedidos" Member="Pedidos">
    <Type Name="Pedido">
      <Column Name="NumeroPedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Pedido_DetallesPedido" Member="DetallesPedidos" ThisKey="NumeroPedido" OtherKey="NumeroPedido" Type="DetallesPedido" />
      <Association Name="Cliente_Pedido" Member="Cliente" ThisKey="CodigoCliente" OtherKey="Codigo" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Productos" Member="Productos">
    <Type Name="Producto">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdMarca" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UrlImange" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Producto_DetallesPedido" Member="DetallesPedidos" ThisKey="Codigo" OtherKey="CodigoProducto" Type="DetallesPedido" />
      <Association Name="Marca_Producto" Member="Marca" ThisKey="IdMarca" OtherKey="Id" Type="Marca" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Role_Usuario" Member="Usuarios" ThisKey="Id" OtherKey="IdRol" Type="Usuario" />
    </Type>
  </Table>
</Database>